# Generated by Django 6.0.6 on 2026-06-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("standard", models.CharField(max_length=100)),
                ("dob", models.DateField(auto_now_add=True)),
                ("phone", models.CharField(max_length=30)),
                ("place", models.CharField(max_length=100)),
                ("address", models.TextField(max_length=500)),
                ("photo", models.ImageField(upload_to="profile_photos")),
            ],
        ),
    ]
