# Generated by Django 6.0.6 on 2026-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(),
        ),
    ]
