# Generated by Django 6.0.6 on 2026-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0002_alter_student_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="pwrd",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="uname",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
